[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
bootloader_api = "0.11.11"
x86_64 = "0.15"
spin = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
